#!/usr/bin/env python3

import os
import subprocess

s = os.popen("netstat -nr | grep ^default").read()

if len(s) > 0 :
    gw_ip = s.split()[1]

    print(os.popen("arp -an | grep \"" + gw_ip + "\"").read().split()[3], )
