* 第6天

害怕恐龙和怪兽

* 第7天

打针

* 第8天

南瓜肚子疼

萝卜门说： 不要吃掉我们

** Scene 1 幼儿园

早上，在院子里的沙坑玩，南瓜肚子疼，疼的厉害，地上打滚
萝卜门要拉他去找老师，可是南瓜疼的厉害，萝卜们跑去找老师

可是找不到，幼儿园里只有小朋友，大家害怕，老师门一定是跑出去吃烤肉去了
不是不是，他们一定跑出去玩滑梯去了

打电话叫救护车

** Scene 2 飞碟

** Scene 3 回到幼儿园

* 第9天

公园厕所，尿尿后背后出现绿色的门

绿色的森林，美丽的糖果小屋

女巫，要吃小朋友

笼子锁住了白萝卜，让胡萝卜干活并给白萝卜送吃的

逃走，安眠药放到女巫的汤里，把药放到香肠里面给狗狗吃

找手电逃跑

回到公园，发现小朋友们还在玩，但是胡萝卜的口袋里有剩下的一片安眠药

* 第10天

同一个公园，出现粉色的门

门的拉力比较小，温和

走进去之后同样的绿色森林，但是更有活力，有很多可爱的小动物

遇到小仙女，大约是小朋友的头那么高，透明的类蝴蝶翅膀，发出微微的光

他们和小仙女愉快的交谈，小仙女非常的温柔，介绍了这个森林的情况

突然，一只胖兔子跳出来说出了问题，森林里最大的一颗树爷爷生病了，它是森林里年级最大的树

小仙女施展魔法，小朋友们在空中飞行，去看那颗大树，发现它身上长了很小的虫子

小仙女施展魔法试图杀掉虫子，树爷爷感觉舒服了一些，可是小虫子从地下爬不停的出来

地下面一定有虫子的窝，可是小仙女要保护树爷爷，于是胖兔子和小朋友们要去找出虫子的窝，

胖兔子带着他们找到一个山洞，他们打开手电开始往里走，越走越狭窄，最后他们在地上爬

胖兔子放臭屁，他们以为是毒气，要胖兔子用胡萝卜把屁屁堵住，胖兔子不肯

他们在地下找到了虫子的窝，可是他们不知道该怎么办？

胖兔子出主意，把虫子窝拖出去，可是他们谁也不敢碰，小朋友们决定用胖兔子装胡萝卜的包把窝包起来拖出去，可是虫子不停的跑出来，最后把胡萝卜放进去喂虫子们吃

出来以后，把包扔到河里流走了，大树爷爷得救了

小仙女送给了他们一人一个戒指，两个戒指连在一起，他们就可以来到南方森林

* 第11天

** scene 1

爸爸们生病了,孩子们被留在保育院，因为妈妈要照顾爸爸。

半夜，孩子们睡不着，老师睡觉了以后，他们聊天

** scene 2

用戒指去了南方森林，找到小仙女请求她帮忙治疗爸爸

小仙女说她不知道怎么治病，不过她知道有一种药(果子)可以让人吃了变得强壮，也许可以帮到爸爸们

但是这个药(果子)在高高的山上，而且山上有魔法的结界，魔法师无法上去

于是，胖兔子决定跟他们一起去，胖兔子带了很多胡萝卜,小仙女送他们到了结界的边缘

** scene 3 爬山

他们穿上了小仙女准备的厚衣服开始爬山，胖兔子一直吃胡萝卜叫着好冷

孩子们也冻的不行了，他们一个劲儿哆嗦，突然起了大风，他们找到一个山洞，休息一下，胖兔子拿出一个小小水晶球，里面封印了一个魔法，点着了火，让孩子们取暖

孩子们很冷，可是他们不想放弃，休息好了以后，他们再次出发

走到手脚麻木，嘴唇都冻住了，话都说不出来

看到一颗大树,红色的叶子像是火一样，不停的动，好像在燃烧一样，红色的大大的果子

周围有湖水，没有结冰，好奇怪

大兔子把胡萝卜掉到水里了，出来一个老爷爷，要金胡萝卜还是银胡萝卜，可是大兔子只要能吃的
然后，老爷爷就消失在水里了

孩子们想把老爷爷叫上来，可以不出来，于是他们扔东西进去，扔进去一瓶水

老爷爷出来问，你们是要加了苹果汁的水，还是加了臭臭的水

孩子们说要能让爸爸身体好起来的果子，老爷爷说要用东西来换才可以，孩子们问要用什么换？
老爷爷说要好玩的东西，他一个人在这里太寂寞了，于是孩子们把自己带的玩具都拿出来了
都给了老爷爷,换了药,那红红的果子摘下来就变成了橘子

** scene 4 回到家

第12天 早上

他们去医院看爸爸，把果子给爸爸吃了，晚上就接到了医生的电话，说爸爸的身体忽然变好了

* 第13天

因为爸爸的病治好了，孩子们在保育院里玩的很开心，还约定了第二天要去公园一起玩。

** scene 1 公园里

他们玩的很开心，休息的时候，发现一颗奇怪的小树，问了南瓜和西瓜之后，发现只有他们两个才能看到

树的叶子是五颜六色的，每一片都不同

突然，树上慢慢的出现的两个果子，他们用手碰了一下，果子就落入他们手中了

之后，小树慢慢消失了，他们闻了一下，果子非常的香甜，忍不住吃下去了，之后，头顶飞过一只乌鸦，
呱呱的叫声下了他们一跳

他们觉得身体痒痒，他们长出了羽毛，腿也缩短了，嘴巴变尖尖的，变成了乌鸦

惊慌之下，他们挥动手臂，结果飞了起来，他们很快就享受飞行的乐趣

飞了一会儿，累了，就停在楼顶的栏杆上休息

想起妈妈会害怕，决定去找小仙女帮忙

** scene 2 南方森林

他们到了南方森林，开心的飞了一阵，欣赏南方森林的美丽

找到了小仙女，小仙女听了他们的描述，在书上找到了动物果，按图片确认了就是误食了动物果实，
要1天以后才能变回人，可是他们要马上变回去，因为怕妈妈担心

可是小仙女也没办法，于是建议他们去找雪上的老爷爷

** scene 3 雪山

他们飞快就飞上了雪山，找到的树和水塘，可是他们身上什么都没有，没办法呼唤出老爷爷，
他们在雪山上找东西，可是到处都是白雪，什么也找不到

这时候，白萝卜肚子疼，要拉臭臭，于是胡萝卜要他把臭臭拉到池塘里去

老爷爷真的出来了，不过非常生气，大声质问是谁拉的臭臭，白萝卜刚刚答应了一声，就被老爷爷用魔法打倒在地上，
嘴巴里冒着黑烟，羽毛都烧点了一些

然后，老爷爷带他们一起找小仙女，拿出一个可以驱散诅咒的卷轴，但他的魔力不够，要和小仙女一起才能用出来

魔法起作用了，他们变回了人形，感谢了老爷爷和小仙女以后，他们回家了。

* 第14天

** 保育院

白萝卜来的晚了一点点，他很兴奋的跑进来要给大家看他的新衣服，上面有一只怪兽

可以西瓜说衣服很难看，白萝卜很难过，胡萝卜陪他去院子里玩

白萝卜和胡萝卜在保育院里的院子里找到了一颗豌豆，把它埋在了すなば里面，这个时候天开始下雨了，老师喊大家回去洗手吃饭，然后孩子们跑进去吃饭了，在外面地面慢慢变湿了，砂場里面慢慢的变了，有两片小绿叶钻了出来，越长越大，越长越粗，叶子也越来越大，一直把保育院从地面托了起来，一直往上升，升到了高高的天上，一直到白云之上,保育院里面，大家一无所知，还在吃饭，说笑。

吃完了饭，又要出去玩了，老师才发现不对，太阳光很刺眼，风也大，很变冷了，老师出去看了一下才发现，整个保育院在高高的天上，望下面看能看到白云和大地。

地面上很多的警察都来了，可是太高了，飞机都飞不上去。大家不知道该怎么办，这个时候，爸爸妈妈也都来了，很多人在下面哭

从下面看，保育院在高高的空中，来回的摆动，只是很慢，在保育院里面感觉不到，但是警察不敢去碰它

** 南方森林

白萝卜和胡萝卜说要上厕所，用戒指来到了南方森林，去找小仙女，小仙女说这可能是一个巨大的豌豆树,唯一的解决办法就把它重新变成一颗豌豆，需要爬到豌豆树的最上面，找到一朵豌豆花，把它摘下来，可是那个花会开在很高的地方，很难爬上去

小仙女把豪猪先生掉下来的刺用魔法粘在了他们身上，吃下了胖兔子准备的特别的胡萝卜和豆子，站在了院子里，过了一会，开始放屁了，砰的一声，白萝卜放了一个响屁，白萝卜和胡萝卜飞了起来，他们伸长胳膊，抱住了大树，然后胡萝卜又放了一个，他们又飞了起来，就这样，他们一点一点的接近的树顶，找到了那朵花，他们想起来小仙女的话，摘下了花以后，大树很快就会开手收缩变回一颗种子，要尽快的回到保育院才行，拿出了准备好的蜘蛛丝粘在叶子上当作降落伞，跳了下来，回到南方森林，找小仙女退掉身上的刺，跑进了保育院

** 降落

大家都很害怕，老师让小朋友们都躲藏到桌子下面，老师在旁边保护他们，开始下降了，房子剧烈的晃动，西瓜从桌子下面滚了出来，老师离的远没有能抓住他，这时白萝卜跳出来，把西瓜拉回来，降落的时候，孩子们都在抱在一起大叫,西瓜从桌子下面滚了除去，白萝卜勇敢的把他拉了回来

* 第15天

** 南方森林河边

南方森林里，胖兔子躺在河边的大石头上吃胡萝卜，吃的特别开心，这时顺着大河漂下来一个东西

胖兔子好奇把它捞了上来，发现是一个大箱子，关的非常紧，胖兔子费了很大的力气才把箱子打开

发现里面有一个帽子，大兔子好奇的戴到了头上，一下就变小了，好像一个虫子那么小，吓得赶快把帽子摘下来，又变大了

它觉得这个帽子很好玩，抱着帽子高兴的回家了

** 地球

因为保育院要检修，于是，保育院放假一个月。于是萝卜们决定去南方森林玩

** 南方森林里

在森林里散步的萝卜们看到了大河就沿着河走，捡起来几块漂亮的石头，准备拿回去作为给妈妈的礼物

胖兔子高兴拿着帽子走，遇到了萝卜们，他高兴的告诉萝卜们他找到的新玩具，大家决定一起玩，他们都想戴帽子去自己想去的地方
于是他们猜拳，胡萝卜赢了，他想进到蚂蚁的窝里面去，他找到了一个蚂蚁窝，戴上了帽子，变小了

他往蚂蚁窝的洞口走去，他看到很多小虫子，都穿着漂亮的衣服，嘴里说着 快快快，晚了就来不及了 之类的话，他好奇的跟着他们进了蚂蚁洞
发现里面很大，到处都有灯火，有很多的装饰，非常漂亮，原来是蚁王的生日

一辆车子拉出来一个巨大的蚂蚁，一看就很凶，可以胡萝卜完全不怕，因为他知道自己把帽子摘下来就会变大，再大的蚂蚁也会伤到他

蚁王座好以后，昆虫们一个一个站出来，把自己的礼品拿出来，胡萝卜身边的一个瓢虫一直吓得发抖，胡萝卜问他你怎么了
瓢虫说，他的礼物不好，害怕蚁王生气，胡萝卜说，为什么要怕他

蚁王很厉害的，蚂蚁们都怕他，所以都听他的命令,而蚂蚁很多。所以，附近的昆虫也都怕蚁王

虫子们一个拿出礼物，蚁王高兴的话，就笑一下，不然就从鼻子里发出哼的一声，虫子就被吓的发抖，胡萝卜越来越生气，他觉得这样欺负别人是不对的

很快就轮到瓢虫了，瓢虫多哆嗦索的走出来，从包里拿出一个心形的橡子，可是蚁王很生气，这样的东西也敢拿来糊弄我，他举起手大喊，把它拿下

周围的蚂蚁拿着武器走了过来，他们走的不快，看得出来他们并不愿意去伤害瓢虫，可是他们很害怕蚁王

这时，胡萝卜站了出来，大喊：不要伤害他

蚂蚁们停下来，胡萝卜说 我有一个很好的礼物愿意送给你，你能原谅瓢虫吗？

蚁王高兴的说是什么，胡萝卜拿出一个石头说，这可不是普通的石头，是很特别的石头你把他放到头上静静的躺着，你就能吸收它的能量，你的力气会变大很多很多

蚁王高兴极了，他立刻就要变强大，他把所有的虫子和蚂蚁都赶走了，因为他怕别的虫子也吸收了能量

他静静的躺下，把石头放在头上

胡萝卜离开的蚂蚁窝，瓢虫认真的感谢了他，虫子们都散开了，蚂蚁们都在附近，小声议论着，以后他的力气更大，就更可怕了

胡萝卜慢慢退到树后，开始跑，他不想吓到虫子们，他摘下了帽子，变大了，蚂蚁窝里的石头也变大了，一下子就把坏蛋蚁王压在了下面，动弹不得，他大声呼救

蚂蚁们跑进来，看到这情景都吓坏了，可是他们都没有帮忙，他们慢慢退了出去，用土把洞口埋上了

* 第16天

** 南方森林

胡萝卜说 爸爸常常说施比受更有福，我总算明白了，帮助了那些小虫子，我觉得很满足

接下来是白萝卜了，白萝卜非常的高兴，可是他知道该去哪里，他听了胡萝卜的故事觉得很棒，也想作类似的事情，可是去哪里呢？

他抱着帽子到处转，看到地上有一些小虫子忙忙碌碌的爬来爬去，好像很忙，他想赶快去帮助人,就戴上了帽子，变小了

然后他才仔细的看，是一大群コオロギ，他们聚集在一起，很兴奋的样子

白萝卜问 你们在作什么，是不是有什么大虫子要欺负你们

不是阿，我们要比赛看谁力气最大，这是我们一年里最重要的日子

白萝卜发现有很多土堆成的小台子，每个台子下面放着一个长短不同的石头，问了一下才明白，コオロギ会自己跟石头比大小，在和自己最接近的台子上比赛

他很好奇的看着他们比赛，土台上有两只コオロギ张着大嘴巴，两只大大牙齿咬在一起，一只コオロギ用力把另一只举了起来，从台子上扔了下来，掉下来的コオロギ爬起来，摇摇头，站到后面继续观战。

白萝卜连着看了几场比赛，觉得很有意思，他想看清楚一些，也往前面站，又看了一会，比赛很热烈，台下的虫子们也都兴奋的加油，白萝卜也跟着鼓掌加油，这时场上的比赛结束了，又有一只コオロギ跳了上去，大家都等着另一只，可是没有虫子上场，白萝卜觉得有点奇怪，左右看看，想知道为什么下一个选手步上场，可他发现，附近的虫子们都在看着他，快上场阿，他们大喊道。

原来白萝卜站的位置是排队上场的地方，大家都以为他要上场比赛呢

白萝卜有点害怕，说我不是，可是被别的虫子推了上去

上了台，面对コオロギ时，才发现他们的大牙是那么大，那么亮，好像非常坚硬的样子

白萝卜可没有大牙，他开始出汗，手心全都是汉，对手大叫一声，冲了过来

白萝卜赶紧躲开，对手扑空了，快速转身又扑过来，白萝卜再次躲开，又躲了一次，他觉得全身流汗，像是在洗澡一样，对面的コオロギ有点不耐烦了，因为大家都是要比力气，没有谁会一直躲，台下的虫子们也多叽叽喳喳的说，比赛不好看

白萝卜觉得裤兜里面鼓鼓的，原来有一只香蕉，是他带的零食，跟着他一起变小了，对手再次冲过来时，他先是向左闪，然后看着虫子改变方向之后，才突然向右面一跳，然后把香蕉扔到了地上，コオロギ踩到了香蕉，脚下打滑，站不稳，往前冲了好几步，差一点就掉到台子下面去了，他刚刚站稳，这时候，白萝卜从后面冲了上来用身体撞了他的屁股，他没站稳，又往前走了一步，掉到台子下面去了。

白萝卜学着别的虫子的样子，在台上举起手大叫，可是别的虫子都不高兴。

* 第17天

** 南方森林

白萝卜身上有臭臭，胖兔子带他去河边洗澡，他们还跳到河里去洗澡，这时候，在河岸上，树从里伸出一只爪子抓住了帽子，慢慢把帽子拿走了

他们洗完了，爬上了河岸，在大石头上躺了一会，爬起来穿衣服，这时他们才发现帽子不见了

胖兔子气坏了，跳着大叫，小偷，小偷，不要让我抓住你

他们跑去找小仙女，要借用她的镜子，小仙女要了他一些胡萝卜，才把镜子和魔法水晶借给胖兔子

他们回到河边，用镜子查看过去的事情，发现有爪子，让魔镜跟着爪子，发现原来是一只狸

他一路往北走，胖兔子和白萝卜胡萝卜就拿着魔镜跟着走，一直走到了一座大山下面

发现，狸子移动一块大石头，转进洞里去了

胖兔子说这里是去王北方森林的路，也许这个狸子和女巫有关系，于是他们叫下来一个胖鸽子，让他去给小仙女送信

然后，白萝卜和胡萝卜就跟胖兔子进了洞，这时候，魔法水晶用光了，他们就一直在黑黑洞里走，走了很久才重见天日

前面远远的能看到狸子，他们跑起来，狸子也开始跑了

这个时候，小仙女也飞来了，时不时用魔法探查他们的位置，她发现这里竟然已经是北方森林了

** 北方森林

这个时候，被关在笼子里的女巫，非常着急的在大笼子走来走去的

她等着狸子带缩小帽回来，好变小逃出笼子

狸子跑的慢快要被抓住了，他跑到一颗大树的后面，变成了一个石头椅子

胖兔子和白萝卜胡萝卜追了上来，找不到狸子，累坏了的胖兔子一个大屁股坐在了椅子上，说要休息一下

狸子被压的累坏了，好重阿，胖兔子发现椅子在晃动，椅子变小了，缩小成了一堆肉肉，原来是狸子

狸子大叫一声，又变身了，变成老鼠跑了出去，白萝卜和胡萝卜吓了一跳，让老鼠跑了出去

远远的小仙女也飞了过来

小老鼠又变身成了

* appendix

** Thoughts
