#!/usr/bin/python3

import os

s = os.popen("ip route | grep default").read()

if len(s) > 0 :
    gw_ip = s.split()[2]

    print(os.popen("ip neigh | grep \"" + gw_ip + " \"").read().split()[4], end="")
