!$FCORG = %getenv("FCHOME")/org

!include $FCORG/puml-theme-fc.puml

/'
 ' Sequence Diagram
 '/

!procedure $init_seq()
  hide footbox
  autonumber "<b>0 : "
!endprocedure

!procedure $seq_scene($title)
  == $title ==
!endprocedure

!procedure $trans($src, $dst, $msg, $resp)
  $src -> $dst : $msg
  $dst --> $src : $resp
!endprocedure
