/' Usage:
'   !include %getenv("FCHOME")/org/fc.puml
'/

!$BGCOLOR = "#FEFECE"
!$LINECOLOR = "#A80036"

!$ALTBG0 = "#AliceBlue"
!$ALTBG1 = "#Gold"
!$ALTBG2 = "#LightBlue"
!$ALTBG3 = "#LightGreen"
!$ALTBG4 = "#Implementation"

!$LIFE0 = "#EEEEEE"
!$LIFE1 = "#EB937F"
!$LIFE2 = "#Physical"

!$FOCUS = "#Technology/Physical"

<style>
root {
    LineThickness 2
}

groupHeader {
    BackgroundColor IndianRed
    FontColor White
    FontStyle bold
}

title {
    HorizontalAlignment left
    FontSize 21
    FontColor Black
}

ganttDiagram {
    timeline {
        BackgroundColor AliceBlue
        FontStyle Bold
        FontColor brown
        FontSize 20
    }

    task {
        BackGroundColor #FEFECE
        LineColor #A80036

        unstarted {
            BackGroundColor LightGreen
            LineColor #A80036
        }
    }

    closed {
        BackGroundColor application
    }

    separator {
        LineColor white
    }
}

mindmapDiagram {
    node {
        Padding 7
        Margin 10
    }
    boxless {
        FontColor darkgreen
    }
    .focus {
        BackgroundColor $FOCUS
    }
    .important {
        BackgroundColor #FFBBCC
    }
    .working {
        BackgroundColor lightblue
    }
}

wbsDiagram {
    node {
        Padding 7
        Margin 10
    }
    .focus {
        BackgroundColor $FOCUS
        FontStyle bold
    }
    .important {
        BackgroundColor #FFBBCC
        FontStyle bold
    }
    .working {
        BackgroundColor lightblue
        FontStyle bold
    }
}
</style>

skinparam shadowing true

skinparam defaultFontName Noto Sans CJK SC
skinparam defaultFontSize 17
skinparam Padding         1
skinparam BoxPadding      60

skinparam UseBetaStyle true

skinparam activity {
    BackgroundColor $BGCOLOR
    BorderColor     $LINECOLOR
    BorderThickness 1.2
}

skinparam component {
    BackgroundColor $BGCOLOR
    BorderColor     $LINECOLOR
    BorderThickness 1.2

    BackgroundColor<<focus>> $FOCUS
    FontStyle<<focus>>       Bold
}

skinparam note {
    BorderColor     #Bisque
    BackgroundColor #fbfb77/Yellow

    BackgroundColor<<focus>> $FOCUS
    FontColor<<focus>>       Black
    FontStyle<<focus>>       bold
}

skinparam package {
    BackgroundColor #Bisque
    BorderThickness 1.2
    FontColor       #Black
}

skinparam sequence {
    MessageAlign center

    ArrowColor $LINECOLOR
    ArrowThickness 1.3

    LifeLineBorderColor     $LINECOLOR
    LifeLineBackgroundColor #EEEEEE

    ParticipantBorderColor     $LINECOLOR
    ParticipantBorderThickness 2
    ParticipantBackgroundColor $BGCOLOR
    ParticipantPadding         5

    DividerFontColor       #White
    DividerBackgroundColor #IndianRed

    BoxBackgroundColor #Beige

    ReferenceBorderColor           $LINECOLOR
    ReferenceBackgroundColor       #Technology
    ReferenceHeaderBackgroundColor #Business
}

skinparam state {
    StartColor #MediumBlue
    EndColor   #Red

    BackgroundColor #Implementation
    BorderColor     $LINECOLOR
    BorderThickness 2

    BackgroundColor<<Stable>> #Snow
    BorderThickness<<Stable>> 3

    BackgroundColor<<Transient>> #LightGreen
    BorderThickness<<Transient>> 1
}

skinparam title {
}

skinparam actor {
    BackgroundColor #Yellow/Orange
    BorderColor     $LINECOLOR
    BorderThickness 2
}

skinparam class {
    BackgroundColor $BGCOLOR
    ArrowColor      $LINECOLOR
    BorderColor     $LINECOLOR
    arrowThickness  2
}
