/' Usage:
 '   !include %getenv("FCHOME")/org/fc.puml
 '/

!$BGCOLOR = "#FEFECE"
!$LINECOLOR = "#A80036"

!$ALTBG0 = "#AliceBlue"
!$ALTBG1 = "#Gold"
!$ALTBG2 = "#LightBlue"
!$ALTBG3 = "#LightGreen"
!$ALTBG4 = "#Pink"

!$LIFE1 = "#EB937F"
!$LIFE2 = "#Physical"

<style>
groupHeader {
  BackgroundColor IndianRed
  FontColor White
  FontStyle bold
}

title {
  HorizontalAlignment left
  FontSize 21
  FontColor Black
}

ganttDiagram {
  timeline {
    BackgroundColor AliceBlue
    FontStyle Bold
    FontColor brown
    FontSize 20
  }

  task {
    BackGroundColor #FEFECE
    LineColor #A80036

    unstarted {
      BackGroundColor LightGreen
      LineColor #A80036
    }
  }

  closed {
    BackGroundColor application
  }

  separator {
    LineColor white
  }
}

mindmapDiagram {
  node {
    BackgroundColor lightGreen
  }
  boxless {
    FontColor darkgreen
  }

  .important {
    BackgroundColor #FFBBCC
  }
  .working {
    BackgroundColor lightblue
  }
}

</style>

skinparam shadowing true

skinparam defaultFontName Noto Sans CJK SC
skinparam defaultFontSize 17
skinparam backgroundColor $BGCOLOR
skinparam Padding         1
skinparam BoxPadding      60

skinparam UseBetaStyle true

skinparam activity {
  BackgroundColor $BGCOLOR
  BorderColor $LINECOLOR
  BorderThickness 1.2
}

skinparam component {
  BackgroundColor $BGCOLOR
  BorderColor $LINECOLOR
  BorderThickness 1.2

  BackgroundColor<<focus>> %darken($BGCOLOR, 5)
  FontStyle<<focus>> Bold
}

skinparam note {
  BorderColor $LINECOLOR
  BackgroundColor #fbfb77

  BackgroundColor<<focus>> Yellow
  FontColor<<focus>> Black
  FontStyle<<focus>> bold
}

skinparam package {
  BackgroundColor Bisque
  BorderThickness 1.2
  FontColor Black
}

skinparam sequence {
  MessageAlign center

  ArrowColor $LINECOLOR
  ActorBorderColor $LINECOLOR
  ActorBorderThickness 2

  LifeLineBorderColor $LINECOLOR
  LifeLineBackgroundColor #EEEEEE

  ParticipantBorderColor     $LINECOLOR
  ParticipantBorderThickness 2
  ParticipantBackgroundColor $BGCOLOR
  ParticipantPadding         5

  ActorBackgroundColor $BGCOLOR

  DividerFontColor White
  DividerBackgroundColor IndianRed

  BoxBackgroundColor Beige
}

skinparam state {
  StartColor MediumBlue
  EndColor Red
  BackgroundColor $BGCOLOR
  BorderColor $LINECOLOR

  BorderThickness 2
  BackgroundColor Business

  BorderThickness<<Stable>> 3
  BackgroundColor<<Stable>> Snow

  BorderThickness<<Transient>> 1
  BackgroundColor<<Transient>> LightGreen
}

skinparam title {
  BorderRoundCorner 15
  BorderThickness 0
  BorderColor $LINECOLOR
  BackgroundColor Azure
  FontSize 20
}
