/' Usage:
 '   !include %getenv("FCHOME")/org/fc.puml
 '/

!$BGCOLOR = "#FEFECE"
!$LINECOLOR = "#A80036"

!$ALTBG1 = "#Gold"
!$ALTBG2 = "#LightBlue"
!$ALTBG3 = "#LightGreen"
!$ALTBG4 = "#Pink"

<style>
groupHeader {
  BackgroundColor IndianRed
  FontColor White
  FontStyle bold
}

title {
  HorizontalAlignment left
  FontSize 24
  FontColor blue
}

</style>

skinparam shadowing true

skinparam defaultFontName Noto Sans
skinparam defaultFontSize 14
skinparam backgroundColor $BGCOLOR
skinparam Padding         0

skinparam UseBetaStyle true

skinparam activity {
  BackgroundColor $BGCOLOR
  BorderColor $LINECOLOR
  BorderThickness 1.2
}

skinparam component {
  BackgroundColor $BGCOLOR
  BorderColor $LINECOLOR
  BorderThickness 1.2
}

skinparam note {
  BorderColor $LINECOLOR
  BackgroundColor #fbfb77
}

skinparam package {
  BackgroundColor Bisque
  BorderThickness 1.2
  FontColor Black
}

skinparam sequence {
  MessageAlign center

  ArrowColor $LINECOLOR
  ActorBorderColor $LINECOLOR
  ActorBorderThickness 2

  LifeLineBorderColor $LINECOLOR
  LifeLineBackgroundColor #EEEEEE

  ParticipantBorderColor $LINECOLOR
  ParticipantBorderThickness 2
  ParticipantBackgroundColor $BGCOLOR

  ActorBackgroundColor $BGCOLOR

  DividerFontColor White
  DividerBackgroundColor IndianRed
}

skinparam state {
  StartColor MediumBlue
  EndColor Red
  BackgroundColor $BGCOLOR
  BorderColor $LINECOLOR

  BackgroundColor<<Stable>> Snow
}

skinparam title {
  BorderRoundCorner 15
  BorderThickness 0
  BorderColor $LINECOLOR
  BackgroundColor Azure
  FontSize 16
}
